title: Your awesome title
email: education@adicu.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of all ADI-developed curriculum.
baseurl: "/beta"
url: "learn.adicu.com"
github_username: adicu

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

